name: Main PR 후 build 및 jenkins 요청

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  # pull_request:
  #   branches:
  #     - main
  #   types:
  #     - closed  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # 1. 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set repository name to lowercase
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      
      # 2. Docker 이미지 빌드
      - name: Build Docker image
        run: |
          docker build \
          --build-arg NEXT_PUBLIC_WEATHER_KEY=${{ secrets.WEATHER_KEY }} \
           -t ghcr.io/${{ env.REPO_NAME }}:latest -f Docker/Dockerfile .
      
      # 3. GitHub Container Registry 로그인
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      
      # 4. Docker 이미지 푸시
      - name: Push Docker image to GitHub Packages
        run: |
          docker push ghcr.io/${{ env.REPO_NAME }}:latest
      
      # 5. Jenkins Job 호출
      - name: Trigger Jenkins Job
        run: |
          curl -X POST "${{ secrets.JENKINS_URL }}/job/frontend/build" \
          --user "doubly:${{ secrets.JENKINS_API_TOKEN }}"